# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Amol Umrale
tagline:             ''
#description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://amol9.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Amol Umrale
  email:             markdotto@gmail.com
  github:            https://github.com/amol9
  twitter:           https://twitter/babaiscool
  linkedin:          https://linkedin.com/in/amolumrale
  gist:              https://gist.github.com/amol9


# Custom vars
version:             1.0.0


# gems
gems:
 - jekyll-paginate
 - jekyll-gist
 - jekyll_github_sample

kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'


disqus: Amol9


exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
